package osslicenses

// OssLicenseList lists all used libraries and associated OSS Licenses.
const OssLicenseList = `The following software is used by and incorporated into this product:

github.com/aymerick/raymond (MIT)
github.com/blevesearch/bleve (Apache 2.0)
github.com/gorilla/context (New BSD)
github.com/gorilla/handlers (unknown)
github.com/gorilla/mux (New BSD)
github.com/gorilla/sessions (New BSD)
github.com/jmoiron/sqlx (MIT)
github.com/mattbaird/elastigo (Apache 2.0)
github.com/vincent-petithory/dataurl (MIT)
golang.org/x/net (New BSD)
github.com/BurntSushi/toml (unknown)
github.com/robertkrimen/otto (MIT)
github.com/denisenkom/go-mssqldb (New BSD)
github.com/go-ldap/ldap (New BSD)
gopkg.in/mgo.v2/bson (unknown)
github.com/go-sql-driver/mysql (Mozilla Public License 2.0)
github.com/jackc/pgx (MIT)
gopkg.in/airbrake/gobrake.v2 (New BSD)
github.com/xeipuuv/gojsonschema (Apache 2.0, MIT)
golang.org/x/crypto (New BSD)
github.com/go-mangos/mangos (Apache 2.0)
github.com/lib/pq (MIT)
github.com/mattn/go-sqlite3 (MIT)
github.com/boltdb/bolt (MIT)
github.com/jteeuwen/go-bindata (CC0 1.0 Universal (CC0 1.0) Public Domain Dedication)
gopkg.in/fsnotify.v1 (BSD)
github.com/pointlander/peg (BSD)
gopkg.in/mgo.v2 (BSD)
gopkg.in/tomb.v1 (BSD)
golang.org/x/net/websocket (New BSD)
github.com/SAP/go-hdb/driver (Apache 2.0)
golang.org/x/net/http2 (New BSD)
golang.org/x/crypto/pkcs12 (New BSD)
github.com/sideshow/apns2 (MIT)
github.com/garyburd/redigo (Apache 2.0)
github.com/fsouza/go-dockerclient (BSD)
github.com/AnyPresence/surgemq (Apache 2.0)
github.com/surge/glog (Apache 2.0)
github.com/stripe/stripe-go (MIT)
github.com/clbanning/mxj (MIT)
github.com/google/go-gcm (Apache 2.0)
github.com/edganiukov/fcm (MIT)
github.com/Microsoft/go-winio (MIT)
`
