CREATE TABLE IF NOT EXISTS `keys` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `account_id` INTEGER NOT NULL,
  `name` TEXT NOT NULL,
  `key` BLOB NOT NULL,
  UNIQUE (`account_id`, `name`) ON CONFLICT FAIL,
  FOREIGN KEY(`account_id`) REFERENCES `accounts`(`id`) ON DELETE CASCADE
)
