ALTER TABLE stats ALTER COLUMN request_size TYPE BIGINT;
ALTER TABLE stats ALTER COLUMN response_time TYPE BIGINT;
ALTER TABLE stats ALTER COLUMN response_size TYPE BIGINT;
ALTER TABLE stats ALTER COLUMN remote_endpoint_response_time TYPE BIGINT;
