#!/bin/bash

# This script ensures that the path where generated static content will be
# stored is cleaned.

# The path to the generated content.
static="$(pwd)/src/gateway/admin/static"

# Ensure this path is cleaned.
if [ -d "${static}" ]; then
  echo "Static assets dirty.  Cleaning..."
  clean="rm -rf ${static}"
  echo "${clean}"
  if [[ $(${clean}) -ne 0 ]]; then
    echo "Failed to clean static assets: $?"
    exit 1
  fi
fi
