#!/bin/bash

# This script ensures that the path where generated static content will be
# stored exists.

# The path to the generated content.
static="$(pwd)/src/gateway/admin/static"

# Ensure this path exists.
if [ ! -d "${static}" ]; then
  echo "Preparing static assets path..."
  prepare="mkdir -p ${static}"
  echo "${prepare}"
  if [[ $(${prepare}) -ne 0 ]]; then
    echo "Failed to prepare static assets: $?"
    exit 1
  fi
fi
