router.get("/composite", "Composite");
router.get("/echo", "Echo");
router.get("/error", "Error Handling");
router.get("/proxy", "Proxy");
router.get("/proxy_headers", "Proxy Response Header");
router.get("/remote_headers", "Remote Headers");
router.get("/workflow", "Workflow");
router.get("/json", "JSON");
router.get("/set_json", "Set JSON");
router.get("/greetings", "Greetings");
