router.get("/composite", "composite")
router.get("/echo", "echo")
router.get("/error", "error_handling")
router.get("/proxy", "proxy")
router.get("/proxy_headers", "proxy_response_headers")
router.get("/remote_headers", "remote_headers")
router.get("/workflow", "workflow")