#!/bin/sh
# Redirect output to stderr.
exec 1>&2

go vet ./src/...
vetresult=$?

gofiles=$(git diff --cached --name-only --diff-filter=ACMRTX | grep '.go$' | grep -v '_vendor')
[ -z "$gofiles" ] && exit $vetresult

unformatted=$(gofmt -l $gofiles)
[ -z "$unformatted" ] && exit $vetresult

echo >&2 "Go files must be formatted with gofmt. Please run:"
for fn in $unformatted; do
    echo >&2 "  gofmt -w $PWD/$fn"
done

echo "EXIT 1"
exit 1
